// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: sh.tangled.repo.issue.comment

package tangledlex

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("sh.tangled.repo.issue.comment", &RepoIssueComment{})
}

type RepoIssueComment struct {
	LexiconTypeID string   `json:"$type" cborgen:"$type,const=sh.tangled.repo.issue.comment"`
	Body          string   `json:"body" cborgen:"body"`
	CreatedAt     string   `json:"createdAt" cborgen:"createdAt"`
	Issue         string   `json:"issue" cborgen:"issue"`
	Mentions      []string `json:"mentions,omitempty" cborgen:"mentions,omitempty"`
	References    []string `json:"references,omitempty" cborgen:"references,omitempty"`
	ReplyTo       *string  `json:"replyTo,omitempty" cborgen:"replyTo,omitempty"`
}
