// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: sh.tangled.repo.issue.state

package tangledlex

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("sh.tangled.repo.issue.state", &RepoIssueState{})
}

type RepoIssueState struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=sh.tangled.repo.issue.state"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt"`
	Issue         string `json:"issue" cborgen:"issue"`
	// state: state of the issue
	State string `json:"state" cborgen:"state"`
}
