// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: sh.tangled.markup.markdown

package tangledlex

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("sh.tangled.markup.markdown#main", &MarkupMarkdown{})
}

// MarkupMarkdown is a "main" in the sh.tangled.markup.markdown schema.
//
// Tangled Flavored Markdown format text
type MarkupMarkdown struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=sh.tangled.markup.markdown"`
	// blobs: list of blobs referenced in markdown
	Blobs []*lexutil.LexBlob `json:"blobs,omitempty" cborgen:"blobs,omitempty"`
	// original: Original Markdown before post-processing. Used to restore original input on edit.
	Original *string `json:"original,omitempty" cborgen:"original,omitempty"`
	// text: Final post-processed markdown content that will be rendered
	Text string `json:"text" cborgen:"text"`
}
