// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: sh.tangled.repo.pull.status

package tangledlex

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("sh.tangled.repo.pull.status", &RepoPullStatus{})
}

type RepoPullStatus struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=sh.tangled.repo.pull.status"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt"`
	Pull          string `json:"pull" cborgen:"pull"`
	// status: status of the pull request
	Status string `json:"status" cborgen:"status"`
}
