// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: sh.tangled.repo.pull.comment

package tangledlex

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("sh.tangled.repo.pull.comment", &RepoPullComment{})
}

type RepoPullComment struct {
	LexiconTypeID string   `json:"$type" cborgen:"$type,const=sh.tangled.repo.pull.comment"`
	Body          string   `json:"body" cborgen:"body"`
	CreatedAt     string   `json:"createdAt" cborgen:"createdAt"`
	Mentions      []string `json:"mentions,omitempty" cborgen:"mentions,omitempty"`
	Pull          string   `json:"pull" cborgen:"pull"`
	References    []string `json:"references,omitempty" cborgen:"references,omitempty"`
}
