// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: sh.tangled.repo.listRepos

package tangledlex

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// RepoListRepos_ListItem is a "listItem" in the sh.tangled.repo.listRepos schema.
type RepoListRepos_ListItem struct {
	Cid *string `json:"cid,omitempty" cborgen:"cid,omitempty"`
	Uri string  `json:"uri" cborgen:"uri"`
	// value: Embedded sh.tangled.repo record
	Value *lexutil.LexiconTypeDecoder `json:"value" cborgen:"value"`
}

// RepoListRepos_Output is the output of a sh.tangled.repo.listRepos call.
type RepoListRepos_Output struct {
	Cursor *string                   `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*RepoListRepos_ListItem `json:"items" cborgen:"items"`
}

// RepoListRepos calls the XRPC method "sh.tangled.repo.listRepos".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Owner DID whose repo records to list.
func RepoListRepos(ctx context.Context, c lexutil.LexClient, cursor string, limit int64, order string, subject string) (*RepoListRepos_Output, error) {
	var out RepoListRepos_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, lexutil.Query, "", "sh.tangled.repo.listRepos", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
