// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: sh.tangled.repo.issue

package tangledlex

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("sh.tangled.repo.issue", &RepoIssue{})
}

type RepoIssue struct {
	LexiconTypeID string   `json:"$type" cborgen:"$type,const=sh.tangled.repo.issue"`
	Body          *string  `json:"body,omitempty" cborgen:"body,omitempty"`
	CreatedAt     string   `json:"createdAt" cborgen:"createdAt"`
	Mentions      []string `json:"mentions,omitempty" cborgen:"mentions,omitempty"`
	References    []string `json:"references,omitempty" cborgen:"references,omitempty"`
	Repo          string   `json:"repo" cborgen:"repo"`
	Title         string   `json:"title" cborgen:"title"`
}
