// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: sh.tangled.repo

package tangledlex

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("sh.tangled.repo", &Repo{})
}

type Repo struct {
	LexiconTypeID string  `json:"$type" cborgen:"$type,const=sh.tangled.repo"`
	CreatedAt     string  `json:"createdAt" cborgen:"createdAt"`
	Description   *string `json:"description,omitempty" cborgen:"description,omitempty"`
	// knot: knot where the repo was created
	Knot string `json:"knot" cborgen:"knot"`
	// labels: List of labels that this repo subscribes to
	Labels []string `json:"labels,omitempty" cborgen:"labels,omitempty"`
	// name: Cosmetic name of the repo.
	Name *string `json:"name,omitempty" cborgen:"name,omitempty"`
	// repoDid: DID of the repo itself, if assigned
	RepoDid *string `json:"repoDid,omitempty" cborgen:"repoDid,omitempty"`
	// source: source of the repo
	Source *string `json:"source,omitempty" cborgen:"source,omitempty"`
	// spindle: CI runner to send jobs to and receive results from
	Spindle *string `json:"spindle,omitempty" cborgen:"spindle,omitempty"`
	// topics: Topics related to the repo
	Topics []string `json:"topics,omitempty" cborgen:"topics,omitempty"`
	// website: Any URI related to the repo
	Website *string `json:"website,omitempty" cborgen:"website,omitempty"`
}
