// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: sh.tangled.publicKey

package tangledlex

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("sh.tangled.publicKey", &PublicKey{})
}

type PublicKey struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=sh.tangled.publicKey"`
	// createdAt: key upload timestamp
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
	// key: public key contents
	Key string `json:"key" cborgen:"key"`
	// name: human-readable name for this key
	Name string `json:"name" cborgen:"name"`
}
