// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: sh.tangled.string

package tangledlex

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("sh.tangled.string", &String{})
}

type String struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=sh.tangled.string"`
	Contents      string `json:"contents" cborgen:"contents"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt"`
	Description   string `json:"description" cborgen:"description"`
	Filename      string `json:"filename" cborgen:"filename"`
}
